'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';
import { Activity, ArrowRight, CheckCircle2, Clock3, Plus, RefreshCw, Search, ShieldAlert, Sparkles } from 'lucide-react';
import { MetricCard } from '@/components/ui/MetricCard';
import { StatusBadge } from '@/components/ui/StatusBadge';
import { api } from '@/services/api';
import type { DashboardCase } from '@/types';

const money = (value: number) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 }).format(value);
const pct = (value: number) => `${Math.round(value * 100)}%`;

export default function Dashboard() {
  const [cases, setCases] = useState<DashboardCase[]>([]);
  const [loading, setLoading] = useState(true);
  useEffect(() => { api.getDashboardCases().then(setCases).finally(() => setLoading(false)); }, []);
  const active = cases.filter((item) => item.status !== 'RESOLVED').length;
  return <div className="mx-auto max-w-[1510px]">
    <div className="mb-7 flex items-end justify-between"><div><div className="eyebrow mb-2">Wednesday · 23 September 2026</div><h1 className="text-[27px] font-bold tracking-[-0.04em] text-slate-800">Good evening, Analyst</h1><p className="mt-1 text-sm text-slate-500">Here’s the state of your fraud investigations today.</p></div><Link href="/investigate" className="flex items-center gap-2 rounded-xl bg-[#102b4c] px-4 py-2.5 text-xs font-bold text-white shadow-lg shadow-slate-300 transition hover:bg-[#193c65]"><Plus size={16} /> Start investigation</Link></div>
    <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><MetricCard label="Active cases" value={String(active || 4)} detail="Across all queues" trend="12%" icon={Activity} /><MetricCard label="High risk" value="07" detail="Risk score above 80%" tone="red" trend="3 new" icon={ShieldAlert} /><MetricCard label="Awaiting approval" value="03" detail="Analyst action required" tone="amber" icon={Clock3} /><MetricCard label="Resolved today" value="18" detail="+4 vs yesterday" tone="green" trend="22%" icon={CheckCircle2} /></div>

    <div className="mt-7 grid gap-6 xl:grid-cols-[minmax(0,1fr)_330px]">
      <section className="panel overflow-hidden"><div className="flex items-center justify-between border-b border-slate-100 px-6 py-5"><div><h2 className="text-sm font-bold text-slate-800">Investigation queue</h2><p className="mt-1 text-xs text-slate-400">Cases requiring attention across the fraud workflow</p></div><div className="flex items-center gap-2"><button className="flex items-center gap-2 rounded-lg border border-slate-200 px-3 py-2 text-xs font-semibold text-slate-500 hover:bg-slate-50"><Search size={14} /> Filter</button><button className="rounded-lg border border-slate-200 p-2 text-slate-400 hover:bg-slate-50"><RefreshCw size={14} /></button></div></div>
        <div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left"><thead className="bg-slate-50/80 text-[10px] font-bold uppercase tracking-[0.13em] text-slate-400"><tr><th className="px-6 py-3">Case ID</th><th className="px-4 py-3">Transaction</th><th className="px-4 py-3">Customer</th><th className="px-4 py-3">Amount</th><th className="px-4 py-3">Risk</th><th className="px-4 py-3">Confidence</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Updated</th><th className="px-4 py-3"></th></tr></thead><tbody className="divide-y divide-slate-100">{loading ? <tr><td colSpan={9} className="px-6 py-12 text-center text-sm text-slate-400">Loading live queue…</td></tr> : cases.map((item) => <tr key={item.case_id} className="group transition hover:bg-blue-50/30"><td className="px-6 py-4"><Link href={`/cases/${item.case_id}`} className="mono text-xs font-bold text-blue-700 hover:underline">{item.case_id}</Link></td><td className="px-4 py-4"><div className="mono text-xs font-semibold text-slate-700">{item.transaction_id}</div><div className="mt-1 text-[10px] text-slate-400">Card transaction</div></td><td className="px-4 py-4"><span className="mono text-xs text-slate-600">{item.customer_id}</span></td><td className="px-4 py-4 text-xs font-semibold text-slate-700">{money(item.amount)}</td><td className="px-4 py-4"><div className="flex items-center gap-2"><div className="h-1.5 w-14 overflow-hidden rounded-full bg-slate-100"><div className={`h-full rounded-full ${item.risk_score > .8 ? 'bg-red-500' : 'bg-amber-500'}`} style={{ width: `${item.risk_score * 100}%` }} /></div><span className={`text-xs font-bold ${item.risk_score > .8 ? 'text-red-600' : 'text-amber-600'}`}>{pct(item.risk_score)}</span></div></td><td className="px-4 py-4 text-xs font-semibold text-slate-600">{pct(item.confidence)}</td><td className="px-4 py-4"><StatusBadge status={item.status} /></td><td className="px-4 py-4 text-xs text-slate-400">{item.case_id === 'CASE-1024' ? '2 min ago' : item.status === 'RESOLVED' ? '1h ago' : '32 min ago'}</td><td className="px-4 py-4"><Link href={`/cases/${item.case_id}`} className="flex h-8 w-8 items-center justify-center rounded-lg text-slate-300 transition group-hover:bg-white group-hover:text-blue-600"><ArrowRight size={16} /></Link></td></tr>)}</tbody></table></div>
        <div className="flex items-center justify-between border-t border-slate-100 px-6 py-4 text-xs text-slate-400"><span>Showing {cases.length || 4} of 24 cases</span><button className="font-semibold text-blue-600">View all cases →</button></div>
      </section>
      <aside className="space-y-6"><div className="rounded-2xl bg-[#102b4c] p-6 text-white shadow-xl shadow-slate-300/40"><div className="mb-6 flex items-start justify-between"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-cyan-300/15 text-cyan-300"><Sparkles size={20} /></div><span className="rounded-full bg-emerald-300/10 px-2.5 py-1 text-[10px] font-bold text-emerald-300">LIVE DEMO</span></div><h3 className="text-lg font-bold tracking-tight">Follow CASE-1024<br />from signal to resolution.</h3><p className="mt-2 text-xs leading-5 text-slate-300">See how the agent combines graph evidence, uncertainty and human approval into a defensible action.</p><Link href="/cases/CASE-1024" className="mt-6 flex items-center justify-between rounded-xl bg-white/10 px-4 py-3 text-xs font-bold transition hover:bg-white/15">Open hero case <ArrowRight size={15} /></Link></div><div className="panel p-5"><div className="mb-4 flex items-center justify-between"><h3 className="text-sm font-bold text-slate-800">Signal health</h3><span className="flex items-center gap-1.5 text-[10px] font-bold text-emerald-600"><span className="h-1.5 w-1.5 rounded-full bg-emerald-500" /> Nominal</span></div><div className="space-y-4"><HealthRow label="Graph traversal" value="98.7%" /><HealthRow label="Agent response time" value="1.2s" /><HealthRow label="Policy checks" value="100%" /></div></div></aside>
    </div>
  </div>;
}

function HealthRow({ label, value }: { label: string; value: string }) { return <div><div className="mb-1.5 flex justify-between text-xs"><span className="text-slate-500">{label}</span><span className="font-bold text-slate-700">{value}</span></div><div className="h-1.5 rounded-full bg-slate-100"><div className="h-full w-[94%] rounded-full bg-gradient-to-r from-blue-500 to-cyan-400" /></div></div>; }
