'use client';

import { useEffect, useRef, useState } from 'react';
import { AlertCircle, ArrowRight, Bot, Check, CheckCircle2, ChevronDown, Clock3, Database, ExternalLink, FileSearch, GitBranch, Info, LockKeyhole, MessageSquare, Network, ShieldAlert, ShieldCheck, Sparkles, UserCheck, UserRound, X, Zap } from 'lucide-react';
import { GraphCanvas } from '@/components/graph/GraphCanvas';
import { StatusBadge } from '@/components/ui/StatusBadge';
import { api } from '@/services/api';
import type { Actor, Evidence, InvestigationCase, TimelineEvent } from '@/types';

const pct = (value: number) => `${Math.round(value * 100)}%`;
const time = (value: string) => new Intl.DateTimeFormat('en-US', { hour: '2-digit', minute: '2-digit' }).format(new Date(value));

export default function CasePage({ params }: { params: { caseId: string } }) {
  const [caseData, setCaseData] = useState<InvestigationCase | null>(null);
  const [selectedEntity, setSelectedEntity] = useState('TXN-104829');
  const [requesting, setRequesting] = useState(false);
  const [addingEvidence, setAddingEvidence] = useState(false);
  const [approving, setApproving] = useState(false);
  const [customerResponseReady, setCustomerResponseReady] = useState(false);
  const [showApproval, setShowApproval] = useState(false);
  const graphRef = useRef<HTMLDivElement>(null);
  useEffect(() => { api.getCase(params.caseId).then(setCaseData).catch(() => setCaseData(null)); }, [params.caseId]);
  const hasCustomerEvidence = Boolean(caseData?.customer_response);
  const hasCustomerResponse = hasCustomerEvidence || customerResponseReady;
  const isResolved = caseData?.status === 'RESOLVED';
  const uncertainty = caseData ? 1 - caseData.confidence : 0;
  const selectedDetails = caseData?.graph_entities.find((entity) => entity.id === selectedEntity);

  async function requestVerification() { if (!caseData) return; setRequesting(true); setCaseData({ ...caseData, status: 'ASSESSING' }); await api.requestEvidence(caseData.case_id); setCaseData(await api.getCase(caseData.case_id)); setCustomerResponseReady(true); setRequesting(false); }
  async function addCustomerEvidence() { if (!caseData) return; setAddingEvidence(true); const updated = await api.addEvidence(caseData.case_id, { type: 'CUSTOMER_CONFIRMATION', source: 'Controlled customer verification', summary: 'I did not recognize this transaction.', related_entities: ['C-45821', 'TXN-104829'] }); setCaseData(updated); setAddingEvidence(false); }
  async function approveAction() { if (!caseData) return; setShowApproval(false); setApproving(true); setCaseData({ ...caseData, status: 'AWAITING_APPROVAL' }); await new Promise((resolve) => setTimeout(resolve, 500)); setCaseData((current) => current ? { ...current, status: 'EXECUTING' } : current); const updated = await api.takeAction(caseData.case_id, { action: caseData.recommendation.action, approved: true }); setCaseData(updated); setApproving(false); }

  if (!caseData) return <div className="mx-auto flex min-h-[60vh] max-w-[900px] items-center justify-center"><div className="panel flex items-center gap-3 px-6 py-5 text-sm text-slate-500"><Sparkles size={16} className="animate-pulse text-blue-600" /> Loading investigation workspace…</div></div>;
  return <div className="mx-auto max-w-[1540px]">
    <div className="mb-5 flex items-start justify-between"><div><div className="mb-2 flex items-center gap-2 text-[11px] font-semibold text-slate-400"><span>Investigations</span><span>/</span><span className="text-slate-600">{caseData.case_id}</span>{isResolved && <span className="ml-2 flex items-center gap-1 text-emerald-600"><CheckCircle2 size={13} /> Case resolved</span>}</div><div className="flex items-center gap-3"><h1 className="mono text-[22px] font-bold tracking-[-0.03em] text-slate-800">{caseData.case_id}</h1><StatusBadge status={caseData.status} /></div><p className="mt-1 text-xs text-slate-500">Agentic investigation workspace · Last updated {isResolved ? 'just now' : '2 minutes ago'}</p></div><div className="flex items-center gap-2"><button className="flex items-center gap-2 rounded-lg border border-slate-200 bg-white px-3 py-2 text-xs font-semibold text-slate-500"><ExternalLink size={14} /> Export case</button><button className="flex items-center gap-2 rounded-lg border border-slate-200 bg-white px-3 py-2 text-xs font-semibold text-slate-500"><ChevronDown size={14} /> More</button></div></div>

    <section className="panel mb-5 grid grid-cols-2 divide-x divide-slate-100 overflow-hidden md:grid-cols-5"><HeaderMetric label="Transaction" value={caseData.transaction_id} icon={<Database size={15} />} /><HeaderMetric label="Customer" value={caseData.customer_id} icon={<UserRound size={15} />} /><HeaderMetric label="Amount" value={`${caseData.currency === 'USD' ? '$' : ''}${caseData.amount.toLocaleString()}`} icon={<Zap size={15} />} /><HeaderMetric label="Risk score" value={pct(caseData.risk_score)} tone="risk" icon={<ShieldAlert size={15} />} /><HeaderMetric label="Confidence" value={pct(caseData.confidence)} tone={caseData.confidence > .9 ? 'safe' : 'blue'} icon={<Sparkles size={15} />} /></section>

    <section className="mb-5 grid gap-5 lg:grid-cols-[minmax(0,1fr)_310px]"><div className="panel overflow-hidden"><div className="flex items-start justify-between border-b border-slate-100 px-6 py-5"><div><div className="eyebrow mb-2">Case assessment</div><h2 className="text-base font-bold text-slate-800">Risk is not confidence</h2><p className="mt-1 text-xs text-slate-400">Three separate signals keep the analyst’s decision defensible.</p></div><div className="flex items-center gap-2 rounded-lg bg-slate-50 px-3 py-2 text-[10px] font-semibold text-slate-500"><Info size={13} /> Evidence-grounded</div></div><div className="grid gap-6 p-6 md:grid-cols-3"><ScoreMeter label="Risk" value={caseData.risk_score} color="red" detail="Likelihood of harmful activity" /><ScoreMeter label="Confidence" value={caseData.confidence} color={caseData.confidence > .9 ? 'green' : 'blue'} detail="Strength of current evidence" /><ScoreMeter label="Uncertainty" value={uncertainty} color="amber" detail="What remains unresolved" inverse /></div></div><div className="panel p-6"><div className="eyebrow mb-2">Current assessment</div><div className="mb-4 flex items-center gap-2"><div className="flex h-8 w-8 items-center justify-center rounded-lg bg-red-50 text-red-600"><AlertCircle size={17} /></div><div className="text-sm font-bold text-slate-800">{caseData.fraud_patterns[0]?.name ?? 'Pattern assessment'}</div></div><p className="text-xs leading-5 text-slate-500">{caseData.fraud_patterns[0]?.description}</p><div className="mt-5 flex items-center justify-between border-t border-slate-100 pt-4"><span className="text-xs text-slate-400">Pattern confidence</span><span className="text-sm font-bold text-slate-700">{pct(caseData.fraud_patterns[0]?.confidence ?? 0)}</span></div></div></section>

    <div className="grid gap-5 xl:grid-cols-[minmax(0,1.28fr)_minmax(390px,.72fr)]"><div className="space-y-5"><section ref={graphRef} className="panel overflow-hidden"><div className="flex items-start justify-between border-b border-slate-100 px-6 py-5"><div><div className="eyebrow mb-2">TigerGraph network</div><h2 className="text-base font-bold text-slate-800">Connected entity investigation</h2><p className="mt-1 text-xs text-slate-400">Suspicious paths are highlighted in red. Select any entity to inspect it.</p></div><div className="flex items-center gap-2 text-[10px] font-semibold text-slate-400"><span className="h-2 w-2 rounded-full bg-red-400" /> Suspicious path <span className="ml-2 h-2 w-2 rounded-full bg-slate-300" /> Related</div></div><GraphCanvas entities={caseData.graph_entities} relationships={caseData.graph_relationships} selectedEntity={selectedEntity} onSelect={setSelectedEntity} /><div className="flex items-center justify-between border-t border-slate-100 bg-slate-50/70 px-6 py-3 text-[11px] text-slate-500"><span>Selected entity: <span className="mono font-bold text-slate-700">{selectedDetails?.label ?? selectedEntity}</span> <span className="ml-2 text-slate-400">· {selectedDetails?.type} · {selectedDetails?.subtitle}</span></span>{selectedDetails?.risk_score !== undefined && <span className="font-bold text-slate-600">Risk {pct(selectedDetails.risk_score)}</span>}</div></section><EvidencePanel caseData={caseData} onView={(id) => { setSelectedEntity(id); graphRef.current?.scrollIntoView({ behavior: 'smooth', block: 'center' }); }} /></div><div className="space-y-5"><FraudPatternPanel caseData={caseData} /><ExplanationPanel caseData={caseData} />{!hasCustomerResponse && <MissingEvidencePanel status={caseData.status} requesting={requesting} onRequest={requestVerification} />}{customerResponseReady && !hasCustomerEvidence && !isResolved && <CustomerResponsePanel response="I did not recognize this transaction." adding={addingEvidence} onAdd={addCustomerEvidence} />}{hasCustomerEvidence && !isResolved && <CustomerResponsePanel response={caseData.customer_response!} adding={addingEvidence} onAdd={addCustomerEvidence} />}{(hasCustomerEvidence || isResolved) && <RecommendationPanel caseData={caseData} approving={approving} onApprove={() => setShowApproval(true)} />} {!hasCustomerEvidence && <RecommendationPanel caseData={caseData} approving={approving} onApprove={() => setShowApproval(true)} />}</div></div>
    <Timeline events={caseData.timeline} />
    {caseData.case_memory && <div className="mt-5 flex items-start gap-3 rounded-2xl border border-emerald-200 bg-emerald-50 p-5"><div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-emerald-100 text-emerald-700"><BookMarkIcon /></div><div><div className="text-sm font-bold text-emerald-900">Case memory updated</div><div className="mt-1 text-xs leading-5 text-emerald-800/80">{caseData.case_memory}</div></div></div>}
    {showApproval && <ApprovalDialog caseData={caseData} onCancel={() => setShowApproval(false)} onApprove={approveAction} />}
  </div>;
}

function HeaderMetric({ label, value, icon, tone = 'default' }: { label: string; value: string; icon: React.ReactNode; tone?: 'default' | 'risk' | 'blue' | 'safe' }) { const text = tone === 'risk' ? 'text-red-600' : tone === 'safe' ? 'text-emerald-600' : tone === 'blue' ? 'text-blue-600' : 'text-slate-800'; return <div className="px-5 py-4 first:pl-6"><div className="mb-2 flex items-center gap-1.5 text-[10px] font-bold uppercase tracking-[0.12em] text-slate-400">{icon}{label}</div><div className={`mono text-sm font-bold ${text}`}>{value}</div></div>; }

function ScoreMeter({ label, value, detail, color, inverse = false }: { label: string; value: number; detail: string; color: 'red' | 'blue' | 'amber' | 'green'; inverse?: boolean }) { const colors = { red: 'bg-red-500 text-red-600', blue: 'bg-blue-500 text-blue-600', amber: 'bg-amber-400 text-amber-600', green: 'bg-emerald-500 text-emerald-600' }; return <div><div className="mb-2 flex items-end justify-between"><span className="text-sm font-bold text-slate-700">{label}</span><span className={`text-xl font-bold ${colors[color].split(' ')[1]}`}>{pct(value)}</span></div><div className="relative h-2 overflow-hidden rounded-full bg-slate-100"><div className={`h-full rounded-full ${colors[color].split(' ')[0]}`} style={{ width: `${value * 100}%` }} /></div><div className="mt-2 flex items-center gap-1.5 text-[10px] text-slate-400">{inverse ? <AlertCircle size={12} /> : <Info size={12} />}{detail}</div></div>; }

function EvidencePanel({ caseData, onView }: { caseData: InvestigationCase; onView: (id: string) => void }) { return <section className="panel overflow-hidden"><div className="flex items-center justify-between border-b border-slate-100 px-6 py-5"><div><div className="eyebrow mb-2">Evidence ledger</div><h2 className="text-base font-bold text-slate-800">Signals supporting this assessment</h2></div><span className="rounded-full bg-slate-100 px-2.5 py-1 text-[10px] font-bold text-slate-500">{caseData.evidence.length} items</span></div><div className="divide-y divide-slate-100">{caseData.evidence.map((item) => <EvidenceCard key={item.evidence_id} evidence={item} onView={onView} />)}</div></section>; }
function EvidenceCard({ evidence, onView }: { evidence: Evidence; onView: (id: string) => void }) { return <div className="p-5 transition hover:bg-slate-50/60"><div className="flex gap-3"><div className="mt-0.5 flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-blue-50 text-blue-600"><FileSearch size={15} /></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><span className="text-[10px] font-bold uppercase tracking-[0.1em] text-slate-500">{evidence.type.replaceAll('_', ' ')}</span><span className="text-[10px] text-slate-300">·</span><span className="text-[10px] text-slate-400">{time(evidence.timestamp)}</span><span className="ml-auto rounded-full bg-blue-50 px-2 py-0.5 text-[10px] font-bold text-blue-600">{pct(evidence.confidence)} conf.</span></div><div className="mt-1.5 text-xs leading-5 text-slate-600">{evidence.summary}</div><div className="mt-3 flex flex-wrap items-center gap-2"><span className="text-[10px] text-slate-400">Source: <span className="font-semibold text-slate-500">{evidence.source}</span></span><div className="ml-auto flex items-center gap-1.5"><div className="flex gap-1">{evidence.related_entities.slice(0, 3).map((id) => <button onClick={() => onView(id)} key={id} className="mono rounded bg-slate-100 px-1.5 py-1 text-[9px] font-semibold text-slate-500 hover:bg-blue-50 hover:text-blue-600">{id}</button>)}</div><button onClick={() => onView(evidence.related_entities[0])} className="flex items-center gap-1 rounded-lg px-2 py-1 text-[10px] font-bold text-blue-600 hover:bg-blue-50"><Network size={12} /> View in graph</button></div></div></div></div></div>; }

function FraudPatternPanel({ caseData }: { caseData: InvestigationCase }) { const pattern = caseData.fraud_patterns[0]; return <section className="panel p-5"><div className="mb-4 flex items-center justify-between"><div className="flex items-center gap-2"><div className="flex h-8 w-8 items-center justify-center rounded-lg bg-red-50 text-red-600"><ShieldAlert size={16} /></div><div><div className="eyebrow">Fraud pattern</div><div className="mt-1 text-sm font-bold text-slate-800">{pattern.name}</div></div></div><span className="text-sm font-bold text-red-600">{pct(pattern.confidence)}</span></div><p className="text-xs leading-5 text-slate-500">{pattern.description}</p><div className="mt-4 space-y-2 border-t border-slate-100 pt-4">{pattern.indicators.map((indicator) => <div key={indicator} className="flex items-center gap-2 text-xs text-slate-600"><span className="h-1.5 w-1.5 rounded-full bg-red-400" />{indicator}</div>)}</div><div className="mt-4 flex items-center gap-2 text-[10px] font-semibold text-slate-400"><FileSearch size={12} /> Evidence refs: {pattern.evidence_refs.join(' · ')}</div></section>; }
function ExplanationPanel({ caseData }: { caseData: InvestigationCase }) { return <section className="panel p-5"><div className="mb-4 flex items-center gap-2"><div className="flex h-8 w-8 items-center justify-center rounded-lg bg-violet-50 text-violet-600"><Bot size={16} /></div><div><div className="eyebrow">Agent explanation</div><div className="mt-1 text-sm font-bold text-slate-800">Evidence-based assessment</div></div></div><div className="space-y-4"><div><div className="mb-1 text-[10px] font-bold uppercase tracking-[0.1em] text-slate-400">Why this case is suspicious</div><p className="text-xs leading-5 text-slate-600">{caseData.transaction_summary} The graph shows a shared device, linked accounts and a new beneficiary relationship.</p></div><div><div className="mb-1 text-[10px] font-bold uppercase tracking-[0.1em] text-slate-400">Assessment</div><p className="text-xs leading-5 text-slate-600">{caseData.confidence > .9 ? 'Customer denial closes the most important uncertainty. Protective action is now defensible under policy.' : 'Risk is elevated, but customer intent remains unresolved. The agent is requesting controlled evidence before recommending restriction.'}</p></div><div className="flex items-center gap-2 border-t border-slate-100 pt-3 text-[10px] font-semibold text-slate-400"><FileSearch size={12} /> References: EV-001 · EV-002 · EV-003 · EV-004{caseData.customer_response && ' · EV-005'}</div></div></section>; }

function MissingEvidencePanel({ status, requesting, onRequest }: { status: InvestigationCase['status']; requesting: boolean; onRequest: () => void }) { return <section className="rounded-2xl border border-amber-200 bg-amber-50/60 p-5"><div className="mb-4 flex items-start gap-3"><div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-amber-100 text-amber-700"><AlertCircle size={16} /></div><div><div className="eyebrow text-amber-700/70">Missing evidence</div><h2 className="mt-1 text-sm font-bold text-amber-950">Additional evidence needed</h2><p className="mt-1 text-xs leading-5 text-amber-900/70">Current confidence is not sufficient for restricted action.</p></div></div><div className="space-y-2 border-y border-amber-200/70 py-3"><div className="flex items-center gap-2 text-xs font-semibold text-amber-900"><span className="h-1.5 w-1.5 rounded-full bg-amber-500" />Customer Transaction Confirmation</div><div className="flex items-center gap-2 text-xs font-semibold text-amber-900"><span className="h-1.5 w-1.5 rounded-full bg-amber-500" />Device Ownership Verification</div></div>{status === 'WAITING_FOR_EVIDENCE' ? <div className="mt-4 flex items-center gap-2 text-xs font-bold text-amber-800"><Clock3 size={14} /> Waiting for customer response…</div> : <button onClick={onRequest} disabled={requesting} className="mt-4 flex w-full items-center justify-center gap-2 rounded-xl bg-amber-600 px-4 py-3 text-xs font-bold text-white shadow-lg shadow-amber-200 transition hover:bg-amber-700 disabled:opacity-60">{requesting ? 'Requesting…' : 'Request customer verification'} <ArrowRight size={14} /></button>}</section>; }
function CustomerResponsePanel({ response, adding, onAdd }: { response: string; adding: boolean; onAdd: () => void }) { return <section className="rounded-2xl border border-blue-200 bg-blue-50/60 p-5"><div className="mb-4 flex items-center gap-3"><div className="flex h-8 w-8 items-center justify-center rounded-lg bg-blue-100 text-blue-700"><MessageSquare size={16} /></div><div><div className="eyebrow text-blue-700/70">Evidence received</div><h2 className="mt-1 text-sm font-bold text-blue-950">Customer response is ready</h2></div></div><blockquote className="rounded-xl border border-blue-100 bg-white/70 p-3 text-xs italic leading-5 text-slate-600">“{response}”</blockquote><button onClick={onAdd} disabled={adding} className="mt-4 flex w-full items-center justify-center gap-2 rounded-xl bg-blue-700 px-4 py-3 text-xs font-bold text-white shadow-lg shadow-blue-200 transition hover:bg-blue-800 disabled:opacity-60">{adding ? 'Adding evidence…' : 'Add evidence to case'} <Check size={14} /></button></section>; }
function RecommendationPanel({ caseData, approving, onApprove }: { caseData: InvestigationCase; approving: boolean; onApprove: () => void }) { const requiresApproval = caseData.recommendation.approval_required && !['RESOLVED', 'EXECUTING'].includes(caseData.status); return <section className={`rounded-2xl border p-5 ${caseData.status === 'RESOLVED' ? 'border-emerald-200 bg-emerald-50/70' : 'border-slate-200 bg-white shadow-panel'}`}><div className="mb-4 flex items-start justify-between"><div className="flex items-center gap-2"><div className={`flex h-8 w-8 items-center justify-center rounded-lg ${caseData.status === 'RESOLVED' ? 'bg-emerald-100 text-emerald-700' : 'bg-[#102b4c] text-cyan-300'}`}><Zap size={16} /></div><div><div className="eyebrow">Next best action</div><h2 className="mt-1 text-sm font-bold text-slate-800">{caseData.status === 'RESOLVED' ? 'Protective action completed' : 'Recommended response'}</h2></div></div><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${caseData.recommendation.approval_required ? 'bg-red-50 text-red-600' : 'bg-blue-50 text-blue-600'}`}>{caseData.recommendation.approval_required ? 'Approval required' : 'Agent recommendation'}</span></div><div className="rounded-xl border border-slate-100 bg-slate-50/70 p-3"><div className="mono text-[13px] font-bold text-slate-800">{caseData.recommendation.action.replaceAll(' · ', ' + ')}</div><div className="mt-2 text-xs leading-5 text-slate-500">{caseData.recommendation.reason}</div></div><div className="mt-4 grid grid-cols-2 gap-3 text-[10px]"><div><div className="text-slate-400">Confidence</div><div className="mt-1 font-bold text-slate-700">{pct(caseData.recommendation.confidence)}</div></div><div><div className="text-slate-400">Policy basis</div><div className="mt-1 font-semibold text-slate-600">{caseData.recommendation.policy_basis}</div></div></div>{requiresApproval && <button onClick={onApprove} disabled={approving} className="mt-5 flex w-full items-center justify-center gap-2 rounded-xl bg-[#102b4c] px-4 py-3 text-xs font-bold text-white shadow-lg shadow-slate-200 transition hover:bg-[#193c65] disabled:opacity-60"><LockKeyhole size={14} /> Review and approve action <ArrowRight size={14} /></button>}{caseData.status === 'RESOLVED' && <div className="mt-5 flex items-center gap-2 rounded-xl bg-emerald-100 px-3 py-2.5 text-xs font-bold text-emerald-800"><CheckCircle2 size={15} /> Transaction blocked · Account frozen</div>}</section>; }
function Timeline({ events }: { events: TimelineEvent[] }) { const actors: Record<Actor, { icon: typeof Bot; color: string }> = { Agent: { icon: Bot, color: 'bg-violet-50 text-violet-600' }, TigerGraph: { icon: Network, color: 'bg-blue-50 text-blue-600' }, Analyst: { icon: UserCheck, color: 'bg-amber-50 text-amber-600' }, Customer: { icon: MessageSquare, color: 'bg-cyan-50 text-cyan-600' }, System: { icon: GitBranch, color: 'bg-slate-100 text-slate-600' } }; return <section className="panel mt-5 overflow-hidden"><div className="border-b border-slate-100 px-6 py-5"><div className="eyebrow mb-2">Case record</div><h2 className="text-base font-bold text-slate-800">Investigation timeline</h2><p className="mt-1 text-xs text-slate-400">A reproducible history across agent, graph, analyst, customer and system events.</p></div><div className="grid gap-x-8 gap-y-0 p-6 md:grid-cols-2">{events.map((event, index) => { const actor = actors[event.actor]; const Icon = actor.icon; return <div key={event.event_id} className="relative flex gap-3 pb-5 last:pb-0"><div className={`relative z-10 flex h-8 w-8 shrink-0 items-center justify-center rounded-lg ${actor.color}`}><Icon size={15} /></div><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><span className="text-[10px] font-bold uppercase tracking-[0.1em] text-slate-400">{event.type}</span><span className="text-[10px] text-slate-300">{time(event.timestamp)}</span></div><p className="mt-1 text-xs leading-5 text-slate-600">{event.summary}</p><span className="mt-1 inline-flex rounded bg-slate-100 px-1.5 py-0.5 text-[9px] font-semibold text-slate-400">{event.actor}</span></div>{index < events.length - 1 && <div className="absolute left-4 top-8 h-[calc(100%-22px)] w-px bg-slate-200 md:hidden" />}</div>; })}</div></section>; }
function ApprovalDialog({ caseData, onCancel, onApprove }: { caseData: InvestigationCase; onCancel: () => void; onApprove: () => void }) { return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/45 p-4 backdrop-blur-sm"><div className="w-full max-w-[520px] rounded-2xl bg-white shadow-2xl"><div className="flex items-start justify-between border-b border-slate-100 p-6"><div><div className="eyebrow mb-2">Human approval · restricted action</div><h2 className="text-lg font-bold text-slate-800">Approve protective action?</h2><p className="mt-1 text-xs text-slate-500">Review the agent recommendation and policy basis before execution.</p></div><button onClick={onCancel} className="rounded-lg p-2 text-slate-400 hover:bg-slate-100"><X size={17} /></button></div><div className="space-y-4 p-6"><div className="rounded-xl border border-red-100 bg-red-50/60 p-4"><div className="label text-red-500">Action</div><div className="mt-1 mono text-sm font-bold text-red-800">{caseData.recommendation.action.replaceAll(' · ', ' + ')}</div></div><div className="grid grid-cols-2 gap-3"><DialogFact label="Customer" value={caseData.customer_id} /><DialogFact label="AI confidence" value={pct(caseData.confidence)} /><DialogFact label="Transaction" value={caseData.transaction_id} /><DialogFact label="Status" value="ACTION_READY" /></div><div><div className="label mb-1">Policy basis</div><p className="text-xs leading-5 text-slate-600">{caseData.recommendation.policy_basis}</p></div><div><div className="label mb-1">Supporting evidence</div><div className="flex flex-wrap gap-1.5">{['EV-001 Shared device', 'EV-003 New beneficiary', 'EV-005 Customer denial'].map((item) => <span key={item} className="rounded-md bg-slate-100 px-2 py-1 text-[10px] font-semibold text-slate-600">{item}</span>)}</div></div></div><div className="flex justify-end gap-2 border-t border-slate-100 p-5"><button onClick={onCancel} className="rounded-xl border border-slate-200 px-4 py-2.5 text-xs font-bold text-slate-500 hover:bg-slate-50">Cancel</button><button onClick={onApprove} className="flex items-center gap-2 rounded-xl bg-[#102b4c] px-4 py-2.5 text-xs font-bold text-white hover:bg-[#193c65]"><ShieldCheck size={14} /> Approve & execute</button></div></div></div>; }
function DialogFact({ label, value }: { label: string; value: string }) { return <div className="rounded-xl bg-slate-50 p-3"><div className="label">{label}</div><div className="mono mt-1 text-xs font-bold text-slate-700">{value}</div></div>; }
function BookMarkIcon() { return <svg viewBox="0 0 24 24" width="16" height="16" fill="none" stroke="currentColor" strokeWidth="2"><path d="M6 3h12v18l-6-3-6 3V3Z" /><path d="m9 8 2 2 4-4" /></svg>; }
