'use client';

import { FormEvent, useState } from 'react';
import { useRouter } from 'next/navigation';
import { ArrowRight, Check, ChevronLeft, CircleDot, Database, GitBranch, Loader2, Search, ShieldAlert, Sparkles, UserRound } from 'lucide-react';
import { api } from '@/services/api';
import type { TriggerType } from '@/types';

const steps = ['Opening Case', 'Retrieving Transaction', 'Querying TigerGraph', 'Analyzing Connected Entities', 'Checking Similar Cases', 'Assessing Fraud Patterns'];
const triggerOptions: { value: TriggerType; label: string; description: string; icon: typeof ShieldAlert }[] = [
  { value: 'HIGH_RISK', label: 'High-risk signal', description: 'A model score or rule has flagged activity.', icon: ShieldAlert },
  { value: 'CUSTOMER_REPORT', label: 'Customer report', description: 'A customer reports an unrecognized transaction.', icon: UserRound },
  { value: 'ANALYST_REQUEST', label: 'Analyst request', description: 'Start an investigation from analyst review.', icon: Search },
];

export default function InvestigatePage() {
  const router = useRouter();
  const [transactionId, setTransactionId] = useState('TXN-104829');
  const [trigger, setTrigger] = useState<TriggerType>('HIGH_RISK');
  const [running, setRunning] = useState(false);
  const [step, setStep] = useState(-1);
  const [error, setError] = useState('');
  async function submit(event: FormEvent) { event.preventDefault(); setError(''); setRunning(true); setStep(0); const timer = window.setInterval(() => setStep((value) => value < steps.length - 1 ? value + 1 : value), 520); try { const response = await api.startInvestigation({ transaction_id: transactionId, trigger }); window.clearInterval(timer); setStep(steps.length - 1); await new Promise((resolve) => setTimeout(resolve, 500)); router.push(`/cases/${response.case_id}`); } catch { window.clearInterval(timer); setError('Unable to start investigation. Check the API connection and try again.'); setRunning(false); } }
  return <div className="mx-auto max-w-[1100px]"><div className="mb-8"><a href="/" className="mb-5 inline-flex items-center gap-1 text-xs font-semibold text-slate-400 hover:text-blue-600"><ChevronLeft size={14} /> Back to overview</a><div className="eyebrow mb-2">Agentic workflow · Trigger</div><h1 className="text-[28px] font-bold tracking-[-0.04em] text-slate-800">Start a new investigation</h1><p className="mt-1 text-sm text-slate-500">Give the agent the initial signal. It will build the case, traverse connected entities and surface the next best action.</p></div>
    <div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_350px]"><form onSubmit={submit} className="panel p-7"><div className="mb-7 flex items-center gap-3 border-b border-slate-100 pb-6"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-blue-50 text-blue-600"><Sparkles size={19} /></div><div><h2 className="text-sm font-bold text-slate-800">Investigation trigger</h2><p className="mt-1 text-xs text-slate-400">The starting point is recorded in the case timeline.</p></div></div><label className="label mb-2 block">Transaction ID</label><div className="relative"><Database size={16} className="absolute left-3 top-3 text-slate-400" /><input value={transactionId} onChange={(e) => setTransactionId(e.target.value)} className="h-11 w-full rounded-xl border border-slate-200 bg-slate-50 pl-10 pr-4 font-mono text-sm font-semibold text-slate-700 outline-none transition focus:border-blue-400 focus:bg-white" placeholder="TXN-104829" /></div><div className="mb-2 mt-7 flex items-center justify-between"><label className="label">Trigger type</label><span className="text-[10px] text-slate-400">Required</span></div><div className="space-y-2">{triggerOptions.map((option) => { const Icon = option.icon; const selected = trigger === option.value; return <button type="button" key={option.value} onClick={() => setTrigger(option.value)} className={`flex w-full items-center gap-4 rounded-xl border p-4 text-left transition ${selected ? 'border-blue-300 bg-blue-50/70 ring-2 ring-blue-100' : 'border-slate-200 hover:border-slate-300 hover:bg-slate-50'}`}><div className={`flex h-9 w-9 items-center justify-center rounded-lg ${selected ? 'bg-blue-600 text-white' : 'bg-slate-100 text-slate-500'}`}><Icon size={17} /></div><div className="flex-1"><div className={`text-sm font-bold ${selected ? 'text-blue-900' : 'text-slate-700'}`}>{option.label}</div><div className="mt-1 text-xs text-slate-400">{option.description}</div></div><div className={`h-4 w-4 rounded-full border-2 ${selected ? 'border-blue-600 bg-blue-600 ring-2 ring-blue-100' : 'border-slate-300'}`} /></button>; })}</div>{error && <div className="mt-5 rounded-xl border border-red-100 bg-red-50 p-3 text-xs text-red-600">{error}</div>}<button disabled={running || !transactionId.trim()} className="mt-8 flex h-12 w-full items-center justify-center gap-2 rounded-xl bg-[#102b4c] text-sm font-bold text-white shadow-lg shadow-slate-200 transition hover:bg-[#193c65] disabled:cursor-not-allowed disabled:opacity-60">{running ? <><Loader2 size={16} className="animate-spin" /> Investigating…</> : <><Sparkles size={16} /> Start AI Investigation <ArrowRight size={16} /></>}</button></form>
      <aside className="space-y-5"><div className="panel overflow-hidden"><div className="border-b border-slate-100 p-5"><div className="eyebrow mb-2">What happens next</div><h2 className="text-sm font-bold text-slate-800">Investigation runbook</h2></div><div className="p-5">{steps.map((item, index) => <div key={item} className="relative flex gap-3 pb-5 last:pb-0"><div className={`relative z-10 flex h-6 w-6 shrink-0 items-center justify-center rounded-full border text-[10px] font-bold transition ${index <= step ? 'border-blue-600 bg-blue-600 text-white' : 'border-slate-200 bg-white text-slate-400'}`}>{index < step ? <Check size={12} /> : index === step ? <CircleDot size={12} /> : index + 1}</div>{index < steps.length - 1 && <div className={`absolute left-3 top-6 h-full w-px ${index < step ? 'bg-blue-400' : 'bg-slate-200'}`} /> }<div><div className={`text-xs font-semibold ${index <= step ? 'text-slate-800' : 'text-slate-400'}`}>{item}</div>{index === step && running && <div className="mt-1 text-[10px] text-blue-600">In progress…</div>}</div></div>)}</div></div><div className="rounded-2xl border border-blue-100 bg-blue-50/60 p-5"><div className="mb-3 flex items-center gap-2 text-blue-700"><GitBranch size={16} /><span className="text-xs font-bold">Graph-first investigation</span></div><p className="text-xs leading-5 text-slate-500">The agent uses connected entities and prior case memory as structured evidence—not as an opaque label.</p></div></aside></div>
  </div>;
}
